/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aplikasiPOS.ui;

import com.aplikasiPOS.main.Main;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import com.aplikasiPOS.ui.ProductUI;

/**
 *
 * @author Krizz2ND
 */
public class MainMenu extends javax.swing.JFrame {

    private ProductUI productUI;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnMasterData = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnReport = new javax.swing.JMenu();
        mnDailySalesReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 913, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        mnMasterData.setText("Master Data");

        jMenuItem1.setText("Pengguna");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnMasterData.add(jMenuItem1);

        jMenuItem2.setText("Product");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnMasterData.add(jMenuItem2);

        jMenuItem3.setText("Role Dan Menu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnMasterData.add(jMenuItem3);

        menuBar.add(mnMasterData);

        jMenu2.setText("Transaksi");

        jMenuItem4.setText("Penjualan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        menuBar.add(jMenu2);

        mnReport.setText("Laporan");

        mnDailySalesReport.setText("Laporan Penjualan Harian");
        mnDailySalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDailySalesReportActionPerformed(evt);
            }
        });
        mnReport.add(mnDailySalesReport);

        menuBar.add(mnReport);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public SalesPanel salesPanel;
    PersonPanel personPanel;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        personPanel = null;
        try {
            if (personPanel == null) {
                personPanel = new PersonPanel();
                desktopPane.add(personPanel);
            } else {
                personPanel.toFront();
            }
            personPanel.setVisible(true);
            personPanel.setSelected(true);
            personPanel.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        productUI = null;
        try {
            if (productUI == null) {
                productUI = new ProductUI();
                desktopPane.add(productUI);
            } else {
                productUI.toFront();
            }
            productUI.setVisible(true);
            productUI.setSelected(true);
            productUI.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    RoleAndMenu roleAndMenu;
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        roleAndMenu = null;
        try {
            if (roleAndMenu == null) {
                roleAndMenu = new RoleAndMenu();
                desktopPane.add(roleAndMenu);
            } else {
                roleAndMenu.toFront();
            }
            roleAndMenu.setVisible(true);
            roleAndMenu.setSelected(true);
            roleAndMenu.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        salesPanel = null;
        try {
            if (salesPanel == null) {
                salesPanel = new SalesPanel();
                desktopPane.add(salesPanel);
            } else {
                salesPanel.toFront();
            }
            salesPanel.setVisible(true);
            salesPanel.setSelected(true);
            salesPanel.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    DailySalesReport dailySalesReportPanel;
    private void mnDailySalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDailySalesReportActionPerformed
        dailySalesReportPanel = null;
        try {
            if (dailySalesReportPanel == null) {
                dailySalesReportPanel = new DailySalesReport();
                desktopPane.add(dailySalesReportPanel);
            } else {
                dailySalesReportPanel.toFront();
            }
            dailySalesReportPanel.setVisible(true);
            dailySalesReportPanel.setSelected(true);
            dailySalesReportPanel.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnDailySalesReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnDailySalesReport;
    private javax.swing.JMenu mnMasterData;
    private javax.swing.JMenu mnReport;
    // End of variables declaration//GEN-END:variables
}
