/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aplikasiPOS.ui;

import com.aplikasiPOS.main.Main;
import com.aplikasiPOS.model.Product;
import com.aplikasiPOS.model.Sales;
import com.aplikasiPOS.model.SalesDetail;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Krizz2ND
 */
public class SalesPanel extends javax.swing.JInternalFrame {

    private Sales sales;
    private List<SalesDetail> listSalesDetails = new ArrayList<>();
    private static Logger log = Logger.getLogger(SalesPanel.class);

    /**
     * Creates new form SalesPanel
     */
    public SalesPanel() {
        initComponents();
        tblSales.setAutoCreateColumnsFromModel(false);
        jDateChooser1.setDate(new Date());
        enableForm(false);
        btnDelete.setEnabled(false);
        btnTambah.setEnabled(true);
        btnCancel.setEnabled(false);
        btnEdit.setEnabled(false);
        btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCari = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtTransaksi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLookUp = new javax.swing.JButton();
        lblHarga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Penjualan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mnuFind.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mnuNew.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mnuManuaEdit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mnudelete.png"))); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mnuSave.png"))); // NOI18N
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mnuCancel.png"))); // NOI18N
        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mnudoor.png"))); // NOI18N
        btnExit.setText("Keluar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("Tanggal Transaksi");

        txtBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarangActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Barang");

        btnLookUp.setText("...");
        btnLookUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookUpActionPerformed(evt);
            }
        });

        lblHarga.setText("Rp. 0");

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga Satuan", "Kuantitas", "Sub Total"
            }
        ));
        tblSales.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tblSales);

        jButton1.setText("HAPUS PRODUCT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLookUp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)))
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLookUp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        clearForm();
        enableForm(true);
//pengaturan tombol
        btnDelete.setEnabled(true);
        btnTambah.setEnabled(false);
        btnCancel.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSave.setEnabled(true);
        btnCari.setEnabled(false);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (sales != null) {
            enableForm(true);
            btnDelete.setEnabled(false);
            btnTambah.setEnabled(false);
            btnCancel.setEnabled(true);
            btnEdit.setEnabled(false);
            btnSave.setEnabled(true);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (sales != null) {
            try {
                Main.getSalesService().delete(sales);
                clearForm();
                sales = null;
                refreshTable();
                enableForm(false);
//pengaturan tombol
                btnDelete.setEnabled(false);
                btnTambah.setEnabled(true);
                btnCancel.setEnabled(false);
                btnEdit.setEnabled(false);
                btnSave.setEnabled(false);
            } catch (Exception ex) {
                log.error(ex);
                JOptionPane.showMessageDialog(this,
                        "Data masih digunakan tidak bisa dihapus!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (validateForm()) {
            if (sales == null) {
                sales = new Sales();
            }
            loadFormToModel();
            try {
                Main.getSalesService().save(sales);
                clearForm();
                refreshTable();
                enableForm(false);
//pengaturan tombol
                btnDelete.setEnabled(false);
                btnTambah.setEnabled(true);
                btnCancel.setEnabled(false);
                btnEdit.setEnabled(false);
                btnSave.setEnabled(false);
                btnCari.setEnabled(true);
            } catch (Exception ex) {
                log.error(ex);
                JOptionPane.showMessageDialog(this, "Data gagal disimpan!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearForm();
        enableForm(false);
//pengaturan tombol
        btnDelete.setEnabled(false);
        btnTambah.setEnabled(true);
        btnCancel.setEnabled(false);
        btnEdit.setEnabled(false);
        btnSave.setEnabled(false);
        btnCari.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed

        if (listSalesDetails.isEmpty()) {
            Sales s = new SalesLookUpDialog().getSales();
            if (s != null) {
                sales = Main.getSalesService().getSales(s.getId());
                loadModelToForm();
//edit mode
                btnDelete.setEnabled(true);
                btnTambah.setEnabled(false);
                btnCancel.setEnabled(true);
                btnEdit.setEnabled(true);
                btnSave.setEnabled(false);
            }
        }else{
            JOptionPane.showMessageDialog(this, "BATALKAN TAMBAH BARANG TERLEBIH DAHULU");
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Main.getFrameMenu().salesPanel = null;
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLookUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookUpActionPerformed
        Product p = new ProductLookUpDialog().getProduct();
        if (p != null) {
            boolean isProductInSalesDetails = false;
            for (SalesDetail salesDetail : listSalesDetails) {
                if (salesDetail.getId() != null && salesDetail.getProduct().getId().equals(p.getId())) {
                    salesDetail.setQuantity(salesDetail.getQuantity() + 1);
                    salesDetail.setSubtotal(salesDetail.getPrice().multiply(new BigDecimal(salesDetail.getQuantity())));
                    isProductInSalesDetails = true;
                    break;
                }
            }
            if (isProductInSalesDetails) {
                refreshTable();
                refreshTotalLabel();
            } else {
                addSalesDetail(p);
            }
        }
        jButton1.setEnabled(true);
    }//GEN-LAST:event_btnLookUpActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Main.getFrameMenu().salesPanel = null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void txtBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarangActionPerformed
        String productId = txtBarang.getText();
        try {
//cari apakah barang sudah ada di dalam tblSalesDetail
            Long pId = Long.valueOf(productId);
            boolean isProductInSalesDetails = false;
            for (SalesDetail salesDetail : listSalesDetails) {
                if (salesDetail.getId() != null && salesDetail.getProduct().getId().equals(pId)) {
                    salesDetail.setQuantity(salesDetail.getQuantity() + 1);
                    salesDetail.setSubtotal(salesDetail.getPrice().multiply(new BigDecimal(salesDetail.getQuantity())));
                    isProductInSalesDetails = true;
                    break;
                }
            }
            if (isProductInSalesDetails) {
                refreshTable();
                refreshTotalLabel();
            } else {
                Product p = Main.getProductService().getProduct(pId);
                if (p != null) {
                    addSalesDetail(p);
                }
            }
            txtTransaksi.setText("");
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Id barang harus berupa angka!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtBarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (tblSales.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "PILIH PRODUCT YANG INGIN DI HAPUS");
        } else {
            SalesDetailTableModel dd = new SalesDetailTableModel(listSalesDetails);
            dd.Remove(tblSales.getSelectedRow());
            refreshTable();
            if (listSalesDetails.isEmpty()) {
                jButton1.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearForm() {
        txtBarang.setText("");
        lblHarga.setText("Rp. 0");
        jDateChooser1.setDate(new Date());
        listSalesDetails = new ArrayList<SalesDetail>();
        sales = null;
        tblSales.setModel(new SalesDetailTableModel(listSalesDetails));
    }

    private void enableForm(boolean status) {
        txtTransaksi.setEnabled(status);
        btnLookUp.setEnabled(status);
        tblSales.setEnabled(status);
    }

    private boolean validateForm() {
        if (listSalesDetails == null || listSalesDetails.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Transaksi tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void loadFormToModel() {
        sales.setSalesDetails(listSalesDetails);
        sales.setSalesDate(new Date());
        BigDecimal total = BigDecimal.ZERO;
        for (SalesDetail salesDetail : listSalesDetails) {
            total = total.add(salesDetail.getSubtotal());
            salesDetail.setSales(sales);
        }
        sales.setTotalSales(total);
    }

    private void loadModelToForm() {
        listSalesDetails = sales.getSalesDetails();
        tblSales.setModel(new SalesDetailTableModel(listSalesDetails));
        lblHarga.setText(TextComponentUtils.formatNumber(sales.getTotalSales()));
    }

    private void refreshTable() {
        tblSales.setModel(new SalesDetailTableModel(listSalesDetails));
    }

    private void refreshTotalLabel() {
        if (listSalesDetails != null && !listSalesDetails.isEmpty()) {
            BigDecimal total = BigDecimal.ZERO;
            for (SalesDetail salesDetail : listSalesDetails) {
                total = total.add(salesDetail.getSubtotal());
            }
            lblHarga.setText("Rp. " + TextComponentUtils.formatNumber(total));
        }
    }

    private void addSalesDetail(Product p) {
        if (p != null) {
            SalesDetail salesDetail = new SalesDetail();
            salesDetail.setProduct(p);
            salesDetail.setPrice(p.getPrice());
            salesDetail.setQuantity(1);
            salesDetail.setSubtotal(p.getPrice());

            List<Product> blaa = new ProductLookUpDialog().getProductKo();
            Iterator iter = listSalesDetails.iterator();
            boolean test = false;
            if (!listSalesDetails.isEmpty()) {
                for (SalesDetail listSalesDetail : listSalesDetails) {
                    System.out.println(p.getId());
                    System.out.println(listSalesDetail.getProduct().getId());
                    if (listSalesDetail.getProduct().getId().equals(p.getId())) {
                        listSalesDetail.setQuantity(listSalesDetail.getQuantity() + 1);
                        listSalesDetail.setSubtotal(listSalesDetail.getPrice().multiply(new BigDecimal(listSalesDetail.getQuantity())));
                        System.out.println("itu jalan");
                        refreshTable();
                        refreshTotalLabel();
                        test = true;
                        break;
                    }

                }
                if (!test) {
                    listSalesDetails.add(salesDetail);
                    refreshTable();
                    refreshTotalLabel();
                }
            } else {
                listSalesDetails.add(salesDetail);
                refreshTable();
                refreshTotalLabel();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Barang tidak ada!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private class SalesDetailTableModel extends AbstractTableModel {

        private List<SalesDetail> salesDetails;

        SalesDetailTableModel(List<SalesDetail> salesDetails) {
            this.salesDetails = salesDetails;
        }

        public void Remove(int row) {
            salesDetails.remove(row);
        }

        public int getRowCount() {
            return salesDetails.size();
        }

        public int getColumnCount() {
            return 5;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            SalesDetail s = salesDetails.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return s.getProduct().getId();
                case 1:
                    return s.getProduct().getName();
                case 2:
                    return s.getPrice();
                case 3:
                    return s.getQuantity();
                case 4:
                    return s.getSubtotal();
                default:
                    return "";
            }
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (columnIndex == 2 || columnIndex == 4) {
                return BigDecimal.class;
            } else if (columnIndex == 3) {
                return Integer.class;
            }
            return String.class;
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            if (columnIndex == 3) {
                return true;
            }
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            SalesDetail s = salesDetails.get(rowIndex);
            if (columnIndex == 3) {
                s.setQuantity((Integer) aValue);
                s.setSubtotal(s.getPrice().multiply(new BigDecimal(s.getQuantity())));
                refreshTotalLabel();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLookUp;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JTable tblSales;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JTextField txtTransaksi;
    // End of variables declaration//GEN-END:variables
}
